version: '3.4'
services:
  unit_tests:
    image: unit_tests
    build:
      context: Server/
      target: unit_tests
    ports: 
      - 80:80
    networks: 
      net:
        ipv4_address: 172.30.0.2
  app:
    image: app
    build:
      context: Server/
      target: app
    ports: 
      - 4444:4444
    networks: 
      net:
        ipv4_address: 172.30.0.3
  web_page:
    image: web_page
    build:
      context: WebPage/
    ports: 
      - 8080:8080
    networks: 
      net:
        ipv4_address: 172.30.0.4
    
networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.0/16
