version: '3.4'
services:
  unit_tests:
    image: unit_tests
    build:
      context: Server/
      target: unit_tests
    ports: 
      - 80:80
  app:
    image: app
    build:
      context: Server/
      target: app
    ports: 
      - 4444:4444
  web_page:
    image: web_page
    build:
      context: WebPage/
      target: web_page
    ports: 
      - 8080:8080
