version: '3.4'
services:
  app:
    image: app
    build:
      context: Server/docker/
    ports: 
      - 4444:4444
    networks: 
      net:
        ipv4_address: 172.30.0.3
  web_page:
    image: web_page
    build:
      context: WebPage/docker/
    ports: 
      - 8080:8080
    networks: 
      net:
        ipv4_address: 172.30.0.4
    
networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.0/16
